Graph:
  NotebookName: Trash
  SectionName: "Book 5"
  RefreshPages: False
  EnvPath: # /content/drive/MyDrive/AI/.env
Generator:
  Pages: 1 # number(s) or empty
  PageNo:
  OpenAI:
    Action: False
    ChunkLimit: 1000
  Maya:
    Action: True
    ChunkLimit: 1000
    ModelPath: /Users/ykamoji/Documents/open-ai-audio-transcription/models/ # /content/drive/MyDrive/AI/Models
