Graph:
  NotebookName: Trash
  SectionName: "Book 5"
  RefreshPages: False
  EnvPath: # /content/drive/MyDrive/AI/.env
Generator:
  Pages: 1 # number(s) or empty
  PageNo:
  AudioOutputPath: output/ #/content/drive/MyDrive/AI/Outputs/
  OpenAI:
    Action: False
    ChunkLimit: 1000
  Maya:
    Action: True
    ModelPath: models/ #/content/drive/MyDrive/AI/Models #/Users/ykamoji/Documents/open-ai-audio-transcription/models/
    Characters:
      - Name: David
        Description: "Seductively character, Male voice in their 30s with a American accent. normal pitch, gravelly timbre, conversational pacing, casual tone at mid intensity"
      - Name: Vanessa
        Description: "Seductively character, Female voice in their 30s with a American accent. normal pitch, deep timbre, conversational pacing, casual tone at mid intensity"
      - Name: Blake
        Description: "Seductively character, Male voice in their 30s with a American accent. normal pitch, throaty timbre, conversational pacing, casual tone at mid intensity"
